In [1]:
# Importing Libraries
import pandas as pd
import numpy as np

In [2]:
df= pd.read_excel('Churn_Unclean_Project.xlsx')

In [3]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 542 entries, 0 to 541
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            542 non-null    object
 1   Customer_Name          533 non-null    object
 2   Gender                 536 non-null    object
 3   Age                    536 non-null    float64
 4   State                  531 non-null    object
 5   City                   539 non-null    object
 6   Tenure_Months          534 non-null    float64
 7   Subscription_Type      530 non-null    object
 8   Monthly_Charges        529 non-null    float64
 9   Total_Charges          533 non-null    float64
 10  Contract_Type          538 non-null    object
 11  Payment_Method         526 non-null    object
 12  Internet_Service       535 non-null    object
 13  Tech_Support           530 non-null    object
 14  Senior_Citizen         534 non-null    object
 15  Dependents             539 non-null    object
 16  Churn                  538 non-null    object
 17  Last_Interaction_Date  539 non-null    object
dtypes: float64(4), object(14)
memory usage: 76.3+ KB

In [5]:
df.describe()

              Age  Tenure_Months  Monthly_Charges  Total_Charges
count  536.000000     534.000000       529.000000     533.000000
mean    44.399254      36.406367      1335.269206   49745.287336
std     18.556837      20.669599       715.972838   41644.111657
min      3.000000       1.000000     -2454.770000  -99781.820000
25%     30.000000      19.000000       756.570000   18770.290000
50%     44.000000      38.000000      1306.800000   40649.600000
75%     57.000000      54.000000      1900.650000   75647.400000
max    165.000000      72.000000      2492.510000  171429.830000

In [6]:
df.shape

(542, 18)

In [7]:
# Missing Values

df.isnull().sum()

Customer_ID               0
Customer_Name             9
Gender                    6
Age                       6
State                    11
City                      3
Tenure_Months             8
Subscription_Type        12
Monthly_Charges          13
Total_Charges             9
Contract_Type             4
Payment_Method           16
Internet_Service          7
Tech_Support             12
Senior_Citizen            8
Dependents                3
Churn                     4
Last_Interaction_Date     3
dtype: int64

In [8]:
# Check Duplicate Records

df.duplicated().sum()

7

In [9]:
# Remove Duplicates

df.drop_duplicates(inplace=True)

In [10]:
df.duplicated().sum()

0

In [11]:
df.shape

(535, 18)

In [12]:
# Replace Dirty(NA or Null) values

df.replace(['N/A','NULL','',' '], np.nan, inplace=True)

In [13]:
df.isnull().sum()

Customer_ID               0
Customer_Name             8
Gender                    5
Age                       6
State                    10
City                      5
Tenure_Months             7
Subscription_Type        11
Monthly_Charges          12
Total_Charges             8
Contract_Type             3
Payment_Method           15
Internet_Service          6
Tech_Support             11
Senior_Citizen            7
Dependents                2
Churn                     3
Last_Interaction_Date     2
dtype: int64

In [14]:
# Remove Extra Spaces

df = df.apply(lambda x:x.str.strip() if x.dtype=='object' else x)

In [15]:
# Proper Case

df['Subscription_Type'].value_counts()

Premium     184
Standard    169
Basic       167
basic         2
BASIC         2
Name: Subscription_Type, dtype: int64

In [16]:
#  Proper Case

df['Customer_Name']=df['Customer_Name'].str.title()
df['State']=df['State'].str.title()
df['City']=df['City'].str.title()
df['Subscription_Type']=df['Subscription_Type'].str.title()
df['Contract_Type']=df['Contract_Type'].str.title()
df['Churn']=df['Churn'].str.title()
df['Gender']=df['Gender'].str.title()

In [17]:
df['Subscription_Type'].value_counts()

Premium     184
Basic       171
Standard    169
Name: Subscription_Type, dtype: int64

In [18]:
# standardize Churn Column

df['Churn'].value_counts()

No     405
Yes    127
Name: Churn, dtype: int64

In [19]:
# Converting numeric columns

cols=['Age', 'Tenure_Months','Monthly_Charges', 'Total_Charges']

for c in cols:
    df[c]=pd.to_numeric(df[c],errors='coerce')

In [20]:
df.describe()

              Age  Tenure_Months  Monthly_Charges  Total_Charges
count  529.000000     528.000000       523.000000     527.000000
mean    44.328922      36.518939      1329.967285   49739.683890
std     18.635396      20.659332       713.450173   41633.677902
min      3.000000       1.000000     -2454.770000  -99781.820000
25%     30.000000      19.000000       757.420000   18818.270000
50%     44.000000      38.000000      1295.880000   40649.600000
75%     57.000000      54.000000      1879.020000   75126.770000
max    165.000000      72.000000      2492.510000  171429.830000

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 535 entries, 0 to 541
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            535 non-null    object
 1   Customer_Name          527 non-null    object
 2   Gender                 530 non-null    object
 3   Age                    529 non-null    float64
 4   State                  525 non-null    object
 5   City                   530 non-null    object
 6   Tenure_Months          528 non-null    float64
 7   Subscription_Type      524 non-null    object
 8   Monthly_Charges        523 non-null    float64
 9   Total_Charges          527 non-null    float64
 10  Contract_Type          532 non-null    object
 11  Payment_Method         520 non-null    object
 12  Internet_Service       529 non-null    object
 13  Tech_Support           524 non-null    object
 14  Senior_Citizen         528 non-null    object
 15  Dependents             533 non-null    object
 16  Churn                  532 non-null    object
 17  Last_Interaction_Date  533 non-null    object
dtypes: float64(4), object(14)
memory usage: 79.4+ KB

In [22]:
# Removing Invalid Age

df=df[(df['Age']>=18)&(df['Age']<=100)]

In [23]:
# Remove Negative Charges

df=df[df['Monthly_Charges']>=0]
df=df[df['Total_Charges']>=0]

In [24]:
df.shape

(492, 18)

In [25]:
# Converting Date

df['Last_Interaction_Date']=pd.to_datetime(df['Last_Interaction_Date'],errors='coerce')

C:\Users\sai vasanth\AppData\Local\Temp\ipykernel_2968\1967098944.py:3: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df['Last_Interaction_Date']=pd.to_datetime(df['Last_Interaction_Date'],errors='coerce')

In [26]:
# Fill Missing Values

df['Tech_Support']=df['Tech_Support'].fillna('No')
df['Payment_Method']=df['Payment_Method'].fillna('Unknown')
df['Monthly_Charges']=df['Monthly_Charges'].fillna(df['Monthly_Charges'].mean())
df['Tenure_Months']=df['Tenure_Months'].fillna(df['Tenure_Months'].mean())
df['Age']=df['Age'].fillna(df['Age'].mean())

df['Last_Interaction_Date']=df['Last_Interaction_Date'].fillna(df['Last_Interaction_Date'].median())

In [27]:
# Feature Engineering

# Customer Lifetime Value

df['Customer_Value']=df['Monthly_Charges']*df['Tenure_Months']

In [28]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,Customer_Value
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,2025-12-10,93627.08
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,Month-To-Month,Debit Card,5G,No,No,No,Yes,2026-02-20,7215.39
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,2026-02-04,1884.12
6,C1006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,Month-To-Month,UPI,DSL,Yes,No,No,No,2025-12-26,140618.10
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,2025-01-14,125182.26

In [29]:
# Monthly Revenue

df['Monthly_Revenue']=df['Monthly_Charges']

In [30]:
# Tenure Group "0-12","13-24","25-48","49-72"
bins =[0,12,24,48,72]
label = labels=['0-12 month','13-24 month','25-48 month','49-72 month']
df['Tenure_Group']=pd.cut(df['Tenure_Months'],bins=bins,labels=label)

In [31]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,...,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,Customer_Value,Monthly_Revenue,Tenure_Group
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,...,UPI,Fiber,Yes,No,Yes,No,2025-12-10,93627.08,1614.26,49-72 month
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,...,Debit Card,5G,No,No,No,Yes,2026-02-20,7215.39,555.03,13-24 month
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,...,Debit Card,Cable,Yes,No,No,No,2026-02-04,1884.12,314.02,0-12 month
6,C1006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,...,UPI,DSL,Yes,No,No,No,2025-12-26,140618.10,2008.83,49-72 month
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,...,Cash,Cable,Yes,Yes,Yes,No,2025-01-14,125182.26,2196.18,49-72 month

In [32]:
# Senior Citizen Flag

df['Senior_Flag']=np.where(df['Age']>=60,"Senior",'Adult')

In [33]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,...,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,Customer_Value,Monthly_Revenue,Tenure_Group,Senior_Flag
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,...,Fiber,Yes,No,Yes,No,2025-12-10,93627.08,1614.26,49-72 month,Adult
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,...,5G,No,No,No,Yes,2026-02-20,7215.39,555.03,13-24 month,Adult
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,...,Cable,Yes,No,No,No,2026-02-04,1884.12,314.02,0-12 month,Adult
6,C1006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,...,DSL,Yes,No,No,No,2025-12-26,140618.10,2008.83,49-72 month,Adult
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,...,Cable,Yes,Yes,Yes,No,2025-01-14,125182.26,2196.18,49-72 month,Senior

In [34]:
# Churn flag

df['Churn_Flag']=df["Churn"].map({'Yes':1,'No':0})

In [35]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,...,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,Customer_Value,Monthly_Revenue,Tenure_Group,Senior_Flag,Churn_Flag
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,...,Yes,No,Yes,No,2025-12-10,93627.08,1614.26,49-72 month,Adult,0.0
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,...,No,No,No,Yes,2026-02-20,7215.39,555.03,13-24 month,Adult,1.0
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,...,Yes,No,No,No,2026-02-04,1884.12,314.02,0-12 month,Adult,0.0
6,C1006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,...,Yes,No,No,No,2025-12-26,140618.10,2008.83,49-72 month,Adult,0.0
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,...,Yes,Yes,Yes,No,2025-01-14,125182.26,2196.18,49-72 month,Senior,0.0

In [36]:
# Final checking

df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 492 entries, 0 to 540
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            492 non-null    object
 1   Customer_Name          487 non-null    object
 2   Gender                 488 non-null    object
 3   Age                    492 non-null    float64
 4   State                  485 non-null    object
 5   City                   487 non-null    object
 6   Tenure_Months          492 non-null    float64
 7   Subscription_Type      486 non-null    object
 8   Monthly_Charges        492 non-null    float64
 9   Total_Charges          492 non-null    float64
 10  Contract_Type          490 non-null    object
 11  Payment_Method         492 non-null    object
 12  Internet_Service       486 non-null    object
 13  Tech_Support           492 non-null    object
 14  Senior_Citizen         486 non-null    object
 15  Dependents             491 non-null    object
 16  Churn                  490 non-null    object
 17  Last_Interaction_Date  492 non-null    datetime64[ns]
 18  Customer_Value         492 non-null    float64
 19  Monthly_Revenue        492 non-null    float64
 20  Tenure_Group           492 non-null    category
 21  Senior_Flag            492 non-null    object
 22  Churn_Flag             490 non-null    float64
dtypes: category(1), datetime64[ns](1), float64(7), object(14)
memory usage: 89.1+ KB

In [37]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,...,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,Customer_Value,Monthly_Revenue,Tenure_Group,Senior_Flag,Churn_Flag
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,...,Yes,No,Yes,No,2025-12-10,93627.08,1614.26,49-72 month,Adult,0.0
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,...,No,No,No,Yes,2026-02-20,7215.39,555.03,13-24 month,Adult,1.0
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,...,Yes,No,No,No,2026-02-04,1884.12,314.02,0-12 month,Adult,0.0
6,C1006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,...,Yes,No,No,No,2025-12-26,140618.10,2008.83,49-72 month,Adult,0.0
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,...,Yes,Yes,Yes,No,2025-01-14,125182.26,2196.18,49-72 month,Senior,0.0

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 492 entries, 0 to 540
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            492 non-null    object
 1   Customer_Name          487 non-null    object
 2   Gender                 488 non-null    object
 3   Age                    492 non-null    float64
 4   State                  485 non-null    object
 5   City                   487 non-null    object
 6   Tenure_Months          492 non-null    float64
 7   Subscription_Type      486 non-null    object
 8   Monthly_Charges        492 non-null    float64
 9   Total_Charges          492 non-null    float64
 10  Contract_Type          490 non-null    object
 11  Payment_Method         492 non-null    object
 12  Internet_Service       486 non-null    object
 13  Tech_Support           492 non-null    object
 14  Senior_Citizen         486 non-null    object
 15  Dependents             491 non-null    object
 16  Churn                  490 non-null    object
 17  Last_Interaction_Date  492 non-null    datetime64[ns]
 18  Customer_Value         492 non-null    float64
 19  Monthly_Revenue        492 non-null    float64
 20  Tenure_Group           492 non-null    category
 21  Senior_Flag            492 non-null    object
 22  Churn_Flag             490 non-null    float64
dtypes: category(1), datetime64[ns](1), float64(7), object(14)
memory usage: 89.1+ KB

In [39]:
df.describe()

,Age,Tenure_Months,Monthly_Charges,Total_Charges,Customer_Value,Monthly_Revenue,Churn_Flag
count,492.000000,492.000000,492.000000,492.000000,492.000000,492.000000,490.000000
mean,43.191057,36.059548,1359.222033,50363.987561,50231.467233,1359.222033,0.236735
std,15.401619,20.360662,653.133221,39760.135287,39647.442978,653.133221,0.425513
min,18.000000,1.000000,302.540000,354.120000,379.700000,302.540000,0.000000
25%,30.000000,19.000000,762.940000,19129.100000,19125.137500,762.940000,0.000000
50%,43.000000,37.000000,1308.510000,40668.695000,40701.195000,1308.510000,0.000000
75%,56.000000,53.000000,1889.437500,74393.410000,74097.160000,1889.437500,0.000000
max,70.000000,72.000000,2492.510000,171429.830000,171658.830000,2492.510000,1.000000

In [40]:
df.isnull().sum()

Customer_ID              0
Customer_Name            5
Gender                   4
Age                      0
State                    7
City                     5
Tenure_Months            0
Subscription_Type        6
Monthly_Charges          0
Total_Charges            0
Contract_Type            2
Payment_Method           0
Internet_Service         6
Tech_Support             0
Senior_Citizen           6
Dependents               1
Churn                    2
Last_Interaction_Date    0
Customer_Value           0
Monthly_Revenue          0
Tenure_Group             0
Senior_Flag              0
Churn_Flag               2
dtype: int64

In [41]:
# Exporting Clean Dataset

df.to_csv('Clean_Churn_Data.csv', index=False)

In [42]:
pip install pymysql

Requirement already satisfied: pymysql in c:\users\sai vasanth\anaconda3\lib\site-packages (1.2.0)
Note: you may need to restart the kernel to use updated packages.

In [43]:
# Export into MySQL

from sqlalchemy import create_engine

engine=create_engine("mysql+pymysql://root:"Your Password"@localhost/churndb1")

In [44]:
df.to_sql(
name="customer_churn",
con=engine,
if_exists="replace",
index=False
)

492

In [ ]:
# Connecting MySQL

In [45]:
pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\sai vasanth\anaconda3\lib\site-packages (26.7.0)
Note: you may need to restart the kernel to use updated packages.

In [46]:
import mysql.connector
import pandas as pd

In [48]:
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Your Password",
    database="churndb1",
    use_pure=True
)

In [49]:
print(conn.is_connected())

True

In [50]:
cursor = conn.cursor()

In [51]:
cursor.execute("SHOW TABLES")

for table in cursor.fetchall():
    print(table)

('customer_churn',)

In [52]:
cursor.execute("DESCRIBE customer_churn")

for row in cursor.fetchall():
    print(row)

('Customer_ID', 'text', 'YES', '', None, '')
('Customer_Name', 'text', 'YES', '', None, '')
('Gender', 'text', 'YES', '', None, '')
('Age', 'double', 'YES', '', None, '')
('State', 'text', 'YES', '', None, '')
('City', 'text', 'YES', '', None, '')
('Tenure_Months', 'double', 'YES', '', None, '')
('Subscription_Type', 'text', 'YES', '', None, '')
('Monthly_Charges', 'double', 'YES', '', None, '')
('Total_Charges', 'double', 'YES', '', None, '')
('Contract_Type', 'text', 'YES', '', None, '')
('Payment_Method', 'text', 'YES', '', None, '')
('Internet_Service', 'text', 'YES', '', None, '')
('Tech_Support', 'text', 'YES', '', None, '')
('Senior_Citizen', 'text', 'YES', '', None, '')
('Dependents', 'text', 'YES', '', None, '')
('Churn', 'text', 'YES', '', None, '')
('Last_Interaction_Date', 'datetime', 'YES', '', None, '')
('Customer_Value', 'double', 'YES', '', None, '')
('Monthly_Revenue', 'double', 'YES', '', None, '')
('Tenure_Group', 'text', 'YES', '', None, '')
('Senior_Flag', 'text', 'YES', '', None, '')
('Churn_Flag', 'double', 'YES', '', None, '')

In [53]:
query = "SELECT * FROM customer_churn"

df = pd.read_sql(query, conn)

df.head()

C:\Users\sai vasanth\AppData\Local\Temp\ipykernel_2968\327409447.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,...,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,Customer_Value,Monthly_Revenue,Tenure_Group,Senior_Flag,Churn_Flag
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,...,Yes,No,Yes,No,2025-12-10,93627.08,1614.26,49-72 month,Adult,0.0
1,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,...,No,No,No,Yes,2026-02-20,7215.39,555.03,13-24 month,Adult,1.0
2,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,...,Yes,No,No,No,2026-02-04,1884.12,314.02,0-12 month,Adult,0.0
3,C1006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,...,Yes,No,No,No,2025-12-26,140618.10,2008.83,49-72 month,Adult,0.0
4,C1007,Vikas Yadav,Male,61.0,Delhi,None,57.0,Basic,2196.18,125145.26,...,Yes,Yes,Yes,No,2025-01-14,125182.26,2196.18,49-72 month,Senior,0.0

In [54]:
df.shape

(492, 23)

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 492 entries, 0 to 491
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            492 non-null    object
 1   Customer_Name          487 non-null    object
 2   Gender                 488 non-null    object
 3   Age                    492 non-null    float64
 4   State                  485 non-null    object
 5   City                   487 non-null    object
 6   Tenure_Months          492 non-null    float64
 7   Subscription_Type      486 non-null    object
 8   Monthly_Charges        492 non-null    float64
 9   Total_Charges          492 non-null    float64
 10  Contract_Type          490 non-null    object
 11  Payment_Method         492 non-null    object
 12  Internet_Service       486 non-null    object
 13  Tech_Support           492 non-null    object
 14  Senior_Citizen         486 non-null    object
 15  Dependents             491 non-null    object
 16  Churn                  490 non-null    object
 17  Last_Interaction_Date  492 non-null    datetime64[ns]
 18  Customer_Value         492 non-null    float64
 19  Monthly_Revenue        492 non-null    float64
 20  Tenure_Group           492 non-null    object
 21  Senior_Flag            492 non-null    object
 22  Churn_Flag             490 non-null    float64
dtypes: datetime64[ns](1), float64(7), object(15)
memory usage: 88.5+ KB

In [56]:
df.head(10)

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,...,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,Customer_Value,Monthly_Revenue,Tenure_Group,Senior_Flag,Churn_Flag
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,...,Yes,No,Yes,No,2025-12-10,93627.08,1614.26,49-72 month,Adult,0.0
1,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,...,No,No,No,Yes,2026-02-20,7215.39,555.03,13-24 month,Adult,1.0
2,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,...,Yes,No,No,No,2026-02-04,1884.12,314.02,0-12 month,Adult,0.0
3,C1006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,...,Yes,No,No,No,2025-12-26,140618.10,2008.83,49-72 month,Adult,0.0
4,C1007,Vikas Yadav,Male,61.0,Delhi,None,57.0,Basic,2196.18,125145.26,...,Yes,Yes,Yes,No,2025-01-14,125182.26,2196.18,49-72 month,Senior,0.0
5,C1008,Mohit Arora,Male,45.0,Gujarat,Ahmedabad,63.0,Basic,1200.00,75799.15,...,Yes,No,No,No,2025-02-28,75600.00,1200.00,49-72 month,Adult,0.0
6,C1010,Anjali Mehta,Male,60.0,Delhi,Delhi,12.0,Standard,934.28,11411.36,...,No,Yes,No,Yes,2025-03-10,11211.36,934.28,0-12 month,Senior,1.0
7,C1014,Rahul Singh,Male,41.0,Karnataka,Mysuru,16.0,Premium,2226.93,35184.88,...,Yes,No,No,No,2025-05-10,35630.88,2226.93,13-24 month,Adult,0.0
8,C1015,Pooja Singh,Male,50.0,Delhi,Noida,16.0,Basic,576.03,9489.48,...,No,No,No,No,2026-01-01,9216.48,576.03,13-24 month,Adult,0.0
9,C1018,Amit Sharma,None,41.0,Gujarat,Ahmedabad,48.0,Premium,2328.32,111299.36,...,Yes,No,Yes,No,2025-04-06,111759.36,2328.32,25-48 month,Adult,0.0

In [57]:
query = """
SELECT *
FROM customer_churn
LIMIT 10;
"""

result = pd.read_sql(query, conn)

result

C:\Users\sai vasanth\AppData\Local\Temp\ipykernel_2968\1920929195.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,...,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,Customer_Value,Monthly_Revenue,Tenure_Group,Senior_Flag,Churn_Flag
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,...,Yes,No,Yes,No,2025-12-10,93627.08,1614.26,49-72 month,Adult,0.0
1,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,...,No,No,No,Yes,2026-02-20,7215.39,555.03,13-24 month,Adult,1.0
2,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,...,Yes,No,No,No,2026-02-04,1884.12,314.02,0-12 month,Adult,0.0
3,C1006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,...,Yes,No,No,No,2025-12-26,140618.10,2008.83,49-72 month,Adult,0.0
4,C1007,Vikas Yadav,Male,61.0,Delhi,None,57.0,Basic,2196.18,125145.26,...,Yes,Yes,Yes,No,2025-01-14,125182.26,2196.18,49-72 month,Senior,0.0
5,C1008,Mohit Arora,Male,45.0,Gujarat,Ahmedabad,63.0,Basic,1200.00,75799.15,...,Yes,No,No,No,2025-02-28,75600.00,1200.00,49-72 month,Adult,0.0
6,C1010,Anjali Mehta,Male,60.0,Delhi,Delhi,12.0,Standard,934.28,11411.36,...,No,Yes,No,Yes,2025-03-10,11211.36,934.28,0-12 month,Senior,1.0
7,C1014,Rahul Singh,Male,41.0,Karnataka,Mysuru,16.0,Premium,2226.93,35184.88,...,Yes,No,No,No,2025-05-10,35630.88,2226.93,13-24 month,Adult,0.0
8,C1015,Pooja Singh,Male,50.0,Delhi,Noida,16.0,Basic,576.03,9489.48,...,No,No,No,No,2026-01-01,9216.48,576.03,13-24 month,Adult,0.0
9,C1018,Amit Sharma,None,41.0,Gujarat,Ahmedabad,48.0,Premium,2328.32,111299.36,...,Yes,No,Yes,No,2025-04-06,111759.36,2328.32,25-48 month,Adult,0.0

In [58]:
query = """
SHOW TABLES;
"""

result = pd.read_sql(query, conn)

result

C:\Users\sai vasanth\AppData\Local\Temp\ipykernel_2968\1792559821.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

  Tables_in_churndb1
0     customer_churn

In [60]:
# Average Monthly Charges

query ="""
select AVG(Monthly_Charges) from customer_churn;
"""

result = pd.read_sql(query, conn)

result

C:\Users\sai vasanth\AppData\Local\Temp\ipykernel_2968\2574442305.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

   AVG(Monthly_Charges)
0           1359.222033

In [62]:
# Average Tenure

query ="""
select AVG(Tenure_Months) from customer_churn;
"""

result = pd.read_sql(query, conn)

result

C:\Users\sai vasanth\AppData\Local\Temp\ipykernel_2968\1259794083.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

   AVG(Tenure_Months)
0           36.059548

In [63]:
# Churn by Contract Type

query ="""
select contract_type, count(*) as Customers from customer_churn
group by contract_type;
"""

result = pd.read_sql(query, conn)

result

C:\Users\sai vasanth\AppData\Local\Temp\ipykernel_2968\1613644534.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

    contract_type  Customers
0        One Year        158
1  Month-To-Month        181
2        Two Year        151
3            None          2

In [64]:
# Churn by Internet Service

query ="""
SELECT Internet_Service,
COUNT(*)
FROM customer_churn
GROUP BY Internet_Service;

"""

result = pd.read_sql(query, conn)

result

C:\Users\sai vasanth\AppData\Local\Temp\ipykernel_2968\1433886029.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

  Internet_Service  COUNT(*)
0            Fiber       132
1               5G       117
2            Cable       118
3              DSL       119
4             None         6

In [65]:
# Churn by State

query="""
SELECT State,
COUNT(*)
FROM customer_churn
WHERE Churn='Yes'
GROUP BY State
ORDER BY 2 DESC;

"""
result = pd.read_sql(query, conn)

result

C:\Users\sai vasanth\AppData\Local\Temp\ipykernel_2968\3077459997.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

         State  COUNT(*)
0           Up        29
1        Delhi        24
2    Karnataka        24
3      Gujarat        24
4  Maharashtra        15

In [66]:
# Payment Method Wise Customers

query="""
SELECT Payment_Method,
COUNT(*)
FROM customer_churn
GROUP BY Payment_Method;

"""
result = pd.read_sql(query, conn)

result

C:\Users\sai vasanth\AppData\Local\Temp\ipykernel_2968\2629578423.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

  Payment_Method  COUNT(*)
0            UPI       102
1     Debit Card        98
2           Cash        93
3        Unknown        15
4    Credit Card        93
5    Net Banking        91

In [67]:
# Subscription Type Wise Customers

query="""
SELECT Subscription_Type,
COUNT(*)
FROM customer_churn
GROUP BY Subscription_Type;

"""
result = pd.read_sql(query, conn)

result

C:\Users\sai vasanth\AppData\Local\Temp\ipykernel_2968\1886898530.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

  Subscription_Type  COUNT(*)
0             Basic       154
1           Premium       170
2          Standard       162
3              None         6

In [68]:
# Highest Revenue States

query="""
SELECT State,
SUM(Total_Charges)
FROM customer_churn
GROUP BY State
ORDER BY 2 DESC;

"""
result = pd.read_sql(query, conn)

result

C:\Users\sai vasanth\AppData\Local\Temp\ipykernel_2968\1194260429.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

         State  SUM(Total_Charges)
0        Delhi          5574718.74
1      Gujarat          5009399.95
2           Up          4942209.09
3    Karnataka          4695955.54
4  Maharashtra          4138391.72
5         None           418406.84

In [69]:
# Average Charges by Contract

query="""
SELECT Contract_Type,
AVG(Monthly_Charges)
FROM customer_churn
GROUP BY Contract_Type;

"""
result = pd.read_sql(query, conn)

result

C:\Users\sai vasanth\AppData\Local\Temp\ipykernel_2968\1378313593.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

    Contract_Type  AVG(Monthly_Charges)
0        One Year           1278.951899
1  Month-To-Month           1429.330608
2        Two Year           1354.660861
3            None           1700.105000

In [70]:
# Senior Citizens Churn

query="""
SELECT Senior_Citizen,
COUNT(*)
FROM customer_churn
WHERE Churn='Yes'
GROUP BY Senior_Citizen;

"""
result = pd.read_sql(query, conn)

result

C:\Users\sai vasanth\AppData\Local\Temp\ipykernel_2968\3375070729.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

  Senior_Citizen  COUNT(*)
0             No        93
1            Yes        21
2           None         2

In [71]:
# Top 10 High Value Customers

query="""
SELECT Customer_Name,
Customer_Value
FROM customer_churn
ORDER BY Customer_Value DESC
LIMIT 10;

"""
result = pd.read_sql(query, conn)

result

C:\Users\sai vasanth\AppData\Local\Temp\ipykernel_2968\2330318192.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

  Customer_Name  Customer_Value
0  Anjali Mehta       171658.83
1   Priya Gupta       164738.93
2   Amit Sharma       164458.14
3    Neha Verma       159925.12
4   Amit Sharma       158551.52
5   Mohit Arora       157703.26
6   Rahul Singh       157621.12
7   Vikas Yadav       154889.82
8   Mohit Arora       154598.22
9   Mohit Arora       153188.00

In [72]:
# Customers Without Tech Support

query="""
SELECT *
FROM customer_churn
WHERE Tech_Support='No';

"""
result = pd.read_sql(query, conn)

result

C:\Users\sai vasanth\AppData\Local\Temp\ipykernel_2968\3129485937.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(query, conn)

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,...,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,Customer_Value,Monthly_Revenue,Tenure_Group,Senior_Flag,Churn_Flag
0,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,...,No,No,No,Yes,2026-02-20 00:00:00,7215.39,555.03,13-24 month,Adult,1.0
1,C1010,Anjali Mehta,Male,60.0,Delhi,Delhi,12.0,Standard,934.28,11411.36,...,No,Yes,No,Yes,2025-03-10 00:00:00,11211.36,934.28,0-12 month,Senior,1.0
2,C1015,Pooja Singh,Male,50.0,Delhi,Noida,16.0,Basic,576.03,9489.48,...,No,No,No,No,2026-01-01 00:00:00,9216.48,576.03,13-24 month,Adult,0.0
3,C1019,Anjali Mehta,Male,24.0,Up,Lucknow,22.0,Standard,1151.22,25000.84,...,No,No,Yes,No,2025-05-07 00:00:00,25326.84,1151.22,13-24 month,Adult,0.0
4,C1020,Pooja Singh,Female,22.0,Up,Lucknow,19.0,Premium,1983.04,38142.76,...,No,No,Yes,No,2025-03-27 00:00:00,37677.76,1983.04,13-24 month,Adult,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,C1514,Rahul Singh,Female,61.0,Delhi,Noida,46.0,Premium,556.13,25813.98,...,No,Yes,Yes,No,2025-01-31 00:00:00,25581.98,556.13,25-48 month,Senior,0.0
258,C1517,Amit Sharma,Female,67.0,Karnataka,Mysuru,56.0,Standard,1008.21,56357.76,...,No,Yes,Yes,Yes,2025-08-18 00:00:00,56459.76,1008.21,49-72 month,Senior,1.0
259,C1518,Vikas Yadav,Male,47.0,Maharashtra,Pune,1.0,Premium,2473.81,2618.81,...,No,No,None,Yes,2025-10-11 12:00:00,2473.81,2473.81,0-12 month,Adult,1.0
260,C1522,Mohit Arora,Female,49.0,Up,Kanpur,43.0,Premium,2140.60,92290.80,...,No,None,Yes,Yes,2025-08-15 00:00:00,92045.80,2140.60,25-48 month,Adult,1.0
261,C5002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,...,No,No,No,Yes,2026-02-20 00:00:00,7215.39,555.03,13-24 month,Adult,1.0